from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from research_documentation.analyzers import (
    AnalysisPipeline,
    DependencyGraphAnalyzer,
    RelationshipResolverAnalyzer,
    TypeResolverAnalyzer,
)
from research_documentation.model.software_model import SoftwareModel
from research_documentation.registries import (
    BuilderRegistry,
    ExtractorRegistry,
    RendererRegistry,
    normalize_requested,
)


@dataclass(frozen=True, slots=True)
class DocumentationArtifact:
    """
    Rendered documentation generated by one builder and one renderer.
    """

    builder: str
    renderer: str
    content: str


@dataclass(frozen=True, slots=True)
class DocumentationResult:
    """
    Result of a documentation generation run.
    """

    software_model: SoftwareModel
    built_models: dict[str, Any]
    artifacts: list[DocumentationArtifact]


class DocumentationEngine:
    """
    Public orchestration entry point for documentation generation.
    """

    def __init__(
        self,
        extractor_registry: ExtractorRegistry | None = None,
        builder_registry: BuilderRegistry | None = None,
        renderer_registry: RendererRegistry | None = None,
        analysis_pipeline: AnalysisPipeline | None = None,
        default_builders: Iterable[str] = ("uml",),
        default_renderers: Iterable[str] = ("plantuml",),
    ) -> None:
        self.extractor_registry = (
            extractor_registry or ExtractorRegistry.defaults()
        )
        self.builder_registry = builder_registry or BuilderRegistry.defaults()
        self.renderer_registry = (
            renderer_registry or RendererRegistry.defaults()
        )
        self.analysis_pipeline = analysis_pipeline or self._default_pipeline()
        self.default_builders = tuple(default_builders)
        self.default_renderers = tuple(default_renderers)

    def generate(
        self,
        path: str | Path,
        language: str,
        builders: str | Iterable[str] | None = None,
        renderers: str | Iterable[str] | None = None,
    ) -> DocumentationResult:
        extractor = self.extractor_registry.get(language)
        software_model = extractor.extract(path)
        analyzed_model = self.analysis_pipeline.run(software_model)

        builder_names = normalize_requested(
            builders,
            self.default_builders,
        )
        renderer_names = normalize_requested(
            renderers,
            self.default_renderers,
        )

        built_models = self._build_models(analyzed_model, builder_names)
        artifacts = self._render_artifacts(built_models, renderer_names)

        return DocumentationResult(
            software_model=analyzed_model,
            built_models=built_models,
            artifacts=artifacts,
        )

    def _build_models(
        self,
        software_model: SoftwareModel,
        builder_names: Iterable[str],
    ) -> dict[str, Any]:
        built_models: dict[str, Any] = {}

        for builder_name in builder_names:
            builder = self.builder_registry.get(builder_name)
            built_models[builder_name] = builder.build(software_model)

        return built_models

    def _render_artifacts(
        self,
        built_models: dict[str, Any],
        renderer_names: Iterable[str],
    ) -> list[DocumentationArtifact]:
        artifacts: list[DocumentationArtifact] = []

        for builder_name, built_model in built_models.items():
            for renderer_name in renderer_names:
                renderer = self.renderer_registry.get(renderer_name)
                artifacts.append(
                    DocumentationArtifact(
                        builder=builder_name,
                        renderer=renderer_name,
                        content=renderer.render(built_model),
                    )
                )

        return artifacts

    def _default_pipeline(self) -> AnalysisPipeline:
        return AnalysisPipeline(
            [
                TypeResolverAnalyzer(),
                RelationshipResolverAnalyzer(),
                DependencyGraphAnalyzer(),
            ]
        )
